//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Recruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO_ESTUDIOS
    {
        public int codCentro_Estu { get; set; }
        public bool Tipo { get; set; }
        public string NombreCentroEstudio { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public int codDistrito { get; set; }
    }
}
