//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Recruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int codCliente { get; set; }
        public string R_S_Cliente { get; set; }
        public string Ruc { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public System.DateTime Fec_Reg { get; set; }
        public string Usu_Reg { get; set; }
        public System.DateTime Fec_Mod { get; set; }
        public string Usu_Mod { get; set; }
        public string Contacto { get; set; }
        public int codGiro { get; set; }
        public int codDistrito { get; set; }
        public bool Estado { get; set; }
    }
}
