//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Recruiter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Sistema_RecruiterEntities : DbContext
    {
        public Sistema_RecruiterEntities()
            : base("name=Sistema_RecruiterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CENTRO_ESTUDIOS> CENTRO_ESTUDIOS { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<DISTRITO> DISTRITO { get; set; }
        public virtual DbSet<DOCTORADO> DOCTORADO { get; set; }
        public virtual DbSet<EXPERIENCIA> EXPERIENCIA { get; set; }
        public virtual DbSet<GIRO> GIRO { get; set; }
        public virtual DbSet<IDIOMA_EXTRANJERO> IDIOMA_EXTRANJERO { get; set; }
        public virtual DbSet<MASTER> MASTER { get; set; }
        public virtual DbSet<POSTULANTE> POSTULANTE { get; set; }
        public virtual DbSet<PREGRADO> PREGRADO { get; set; }
        public virtual DbSet<PROCESOS> PROCESOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<DETALLE_DOCTORADO> DETALLE_DOCTORADO { get; set; }
        public virtual DbSet<DETALLE_IDIOMA> DETALLE_IDIOMA { get; set; }
        public virtual DbSet<DETALLE_MASTER> DETALLE_MASTER { get; set; }
        public virtual DbSet<DETALLE_POSTGRADO> DETALLE_POSTGRADO { get; set; }
        public virtual DbSet<DETALLE_PREGRADO> DETALLE_PREGRADO { get; set; }
        public virtual DbSet<DETALLE_PROCESOS> DETALLE_PROCESOS { get; set; }
    
        public virtual int sp_ActualizarCentroEstudio(Nullable<int> cod_cen, Nullable<bool> tipo_cen, string nombre_cen, string direccion_cen, string telefono_cen, string email_cen, Nullable<int> coddis_cen)
        {
            var cod_cenParameter = cod_cen.HasValue ?
                new ObjectParameter("cod_cen", cod_cen) :
                new ObjectParameter("cod_cen", typeof(int));
    
            var tipo_cenParameter = tipo_cen.HasValue ?
                new ObjectParameter("tipo_cen", tipo_cen) :
                new ObjectParameter("tipo_cen", typeof(bool));
    
            var nombre_cenParameter = nombre_cen != null ?
                new ObjectParameter("nombre_cen", nombre_cen) :
                new ObjectParameter("nombre_cen", typeof(string));
    
            var direccion_cenParameter = direccion_cen != null ?
                new ObjectParameter("direccion_cen", direccion_cen) :
                new ObjectParameter("direccion_cen", typeof(string));
    
            var telefono_cenParameter = telefono_cen != null ?
                new ObjectParameter("telefono_cen", telefono_cen) :
                new ObjectParameter("telefono_cen", typeof(string));
    
            var email_cenParameter = email_cen != null ?
                new ObjectParameter("email_cen", email_cen) :
                new ObjectParameter("email_cen", typeof(string));
    
            var coddis_cenParameter = coddis_cen.HasValue ?
                new ObjectParameter("coddis_cen", coddis_cen) :
                new ObjectParameter("coddis_cen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarCentroEstudio", cod_cenParameter, tipo_cenParameter, nombre_cenParameter, direccion_cenParameter, telefono_cenParameter, email_cenParameter, coddis_cenParameter);
        }
    
        public virtual int sp_ActualizarDoctorado(Nullable<int> cod_cen, string nombreDoctorado)
        {
            var cod_cenParameter = cod_cen.HasValue ?
                new ObjectParameter("cod_cen", cod_cen) :
                new ObjectParameter("cod_cen", typeof(int));
    
            var nombreDoctoradoParameter = nombreDoctorado != null ?
                new ObjectParameter("NombreDoctorado", nombreDoctorado) :
                new ObjectParameter("NombreDoctorado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarDoctorado", cod_cenParameter, nombreDoctoradoParameter);
        }
    
        public virtual int sp_ActualizarMaster(Nullable<int> cod_cen, string nombreMaster)
        {
            var cod_cenParameter = cod_cen.HasValue ?
                new ObjectParameter("cod_cen", cod_cen) :
                new ObjectParameter("cod_cen", typeof(int));
    
            var nombreMasterParameter = nombreMaster != null ?
                new ObjectParameter("NombreMaster", nombreMaster) :
                new ObjectParameter("NombreMaster", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarMaster", cod_cenParameter, nombreMasterParameter);
        }
    
        public virtual int sp_ActualziarPostulante(Nullable<int> cod_pos, string nom_pos, string apell_pos, string dni_pos, Nullable<System.DateTime> fecnac_pos, string sexo_pos, string telefono_pos, string email_pos, string direccion_pos, Nullable<System.DateTime> fecreg_pos, string usureg_pos, Nullable<int> codcargo_pos, Nullable<int> coddis_pos, Nullable<int> codpre_pos, Nullable<int> coddoc_pos, Nullable<int> codmaster_pos, Nullable<int> codcen_pos, Nullable<bool> estado_pos)
        {
            var cod_posParameter = cod_pos.HasValue ?
                new ObjectParameter("cod_pos", cod_pos) :
                new ObjectParameter("cod_pos", typeof(int));
    
            var nom_posParameter = nom_pos != null ?
                new ObjectParameter("nom_pos", nom_pos) :
                new ObjectParameter("nom_pos", typeof(string));
    
            var apell_posParameter = apell_pos != null ?
                new ObjectParameter("apell_pos", apell_pos) :
                new ObjectParameter("apell_pos", typeof(string));
    
            var dni_posParameter = dni_pos != null ?
                new ObjectParameter("dni_pos", dni_pos) :
                new ObjectParameter("dni_pos", typeof(string));
    
            var fecnac_posParameter = fecnac_pos.HasValue ?
                new ObjectParameter("fecnac_pos", fecnac_pos) :
                new ObjectParameter("fecnac_pos", typeof(System.DateTime));
    
            var sexo_posParameter = sexo_pos != null ?
                new ObjectParameter("sexo_pos", sexo_pos) :
                new ObjectParameter("sexo_pos", typeof(string));
    
            var telefono_posParameter = telefono_pos != null ?
                new ObjectParameter("telefono_pos", telefono_pos) :
                new ObjectParameter("telefono_pos", typeof(string));
    
            var email_posParameter = email_pos != null ?
                new ObjectParameter("email_pos", email_pos) :
                new ObjectParameter("email_pos", typeof(string));
    
            var direccion_posParameter = direccion_pos != null ?
                new ObjectParameter("direccion_pos", direccion_pos) :
                new ObjectParameter("direccion_pos", typeof(string));
    
            var fecreg_posParameter = fecreg_pos.HasValue ?
                new ObjectParameter("fecreg_pos", fecreg_pos) :
                new ObjectParameter("fecreg_pos", typeof(System.DateTime));
    
            var usureg_posParameter = usureg_pos != null ?
                new ObjectParameter("usureg_pos", usureg_pos) :
                new ObjectParameter("usureg_pos", typeof(string));
    
            var codcargo_posParameter = codcargo_pos.HasValue ?
                new ObjectParameter("codcargo_pos", codcargo_pos) :
                new ObjectParameter("codcargo_pos", typeof(int));
    
            var coddis_posParameter = coddis_pos.HasValue ?
                new ObjectParameter("coddis_pos", coddis_pos) :
                new ObjectParameter("coddis_pos", typeof(int));
    
            var codpre_posParameter = codpre_pos.HasValue ?
                new ObjectParameter("codpre_pos", codpre_pos) :
                new ObjectParameter("codpre_pos", typeof(int));
    
            var coddoc_posParameter = coddoc_pos.HasValue ?
                new ObjectParameter("coddoc_pos", coddoc_pos) :
                new ObjectParameter("coddoc_pos", typeof(int));
    
            var codmaster_posParameter = codmaster_pos.HasValue ?
                new ObjectParameter("codmaster_pos", codmaster_pos) :
                new ObjectParameter("codmaster_pos", typeof(int));
    
            var codcen_posParameter = codcen_pos.HasValue ?
                new ObjectParameter("codcen_pos", codcen_pos) :
                new ObjectParameter("codcen_pos", typeof(int));
    
            var estado_posParameter = estado_pos.HasValue ?
                new ObjectParameter("estado_pos", estado_pos) :
                new ObjectParameter("estado_pos", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualziarPostulante", cod_posParameter, nom_posParameter, apell_posParameter, dni_posParameter, fecnac_posParameter, sexo_posParameter, telefono_posParameter, email_posParameter, direccion_posParameter, fecreg_posParameter, usureg_posParameter, codcargo_posParameter, coddis_posParameter, codpre_posParameter, coddoc_posParameter, codmaster_posParameter, codcen_posParameter, estado_posParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarCentroEstudio_Result> sp_ConsultarCentroEstudio(Nullable<int> cod_cen)
        {
            var cod_cenParameter = cod_cen.HasValue ?
                new ObjectParameter("cod_cen", cod_cen) :
                new ObjectParameter("cod_cen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarCentroEstudio_Result>("sp_ConsultarCentroEstudio", cod_cenParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarPostulante_Result> sp_ConsultarPostulante(Nullable<int> cod_pos)
        {
            var cod_posParameter = cod_pos.HasValue ?
                new ObjectParameter("cod_pos", cod_pos) :
                new ObjectParameter("cod_pos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarPostulante_Result>("sp_ConsultarPostulante", cod_posParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_EliminarCentroEstudio(Nullable<int> cod_cen)
        {
            var cod_cenParameter = cod_cen.HasValue ?
                new ObjectParameter("cod_cen", cod_cen) :
                new ObjectParameter("cod_cen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarCentroEstudio", cod_cenParameter);
        }
    
        public virtual int sp_EliminarPostulante(Nullable<int> cod_pos)
        {
            var cod_posParameter = cod_pos.HasValue ?
                new ObjectParameter("cod_pos", cod_pos) :
                new ObjectParameter("cod_pos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarPostulante", cod_posParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_InsertarCentroEstudio(Nullable<bool> tipo_cen, string nombre_cen, string direccion_cen, string telefono_cen, string email_cen, Nullable<int> coddis_cen)
        {
            var tipo_cenParameter = tipo_cen.HasValue ?
                new ObjectParameter("tipo_cen", tipo_cen) :
                new ObjectParameter("tipo_cen", typeof(bool));
    
            var nombre_cenParameter = nombre_cen != null ?
                new ObjectParameter("nombre_cen", nombre_cen) :
                new ObjectParameter("nombre_cen", typeof(string));
    
            var direccion_cenParameter = direccion_cen != null ?
                new ObjectParameter("direccion_cen", direccion_cen) :
                new ObjectParameter("direccion_cen", typeof(string));
    
            var telefono_cenParameter = telefono_cen != null ?
                new ObjectParameter("telefono_cen", telefono_cen) :
                new ObjectParameter("telefono_cen", typeof(string));
    
            var email_cenParameter = email_cen != null ?
                new ObjectParameter("email_cen", email_cen) :
                new ObjectParameter("email_cen", typeof(string));
    
            var coddis_cenParameter = coddis_cen.HasValue ?
                new ObjectParameter("coddis_cen", coddis_cen) :
                new ObjectParameter("coddis_cen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarCentroEstudio", tipo_cenParameter, nombre_cenParameter, direccion_cenParameter, telefono_cenParameter, email_cenParameter, coddis_cenParameter);
        }
    
        public virtual int sp_InsertarPostulante(string nom_pos, string apell_pos, string dni_pos, Nullable<System.DateTime> fecnac_pos, string sexo_pos, string telefono_pos, string email_pos, string direccion_pos, string usureg_pos, Nullable<int> codcargo_pos, Nullable<int> coddis_pos, Nullable<int> codpre_pos, Nullable<int> coddoc_pos, Nullable<int> codmaster_pos, Nullable<int> codcen_pos, Nullable<bool> estado_pos)
        {
            var nom_posParameter = nom_pos != null ?
                new ObjectParameter("nom_pos", nom_pos) :
                new ObjectParameter("nom_pos", typeof(string));
    
            var apell_posParameter = apell_pos != null ?
                new ObjectParameter("apell_pos", apell_pos) :
                new ObjectParameter("apell_pos", typeof(string));
    
            var dni_posParameter = dni_pos != null ?
                new ObjectParameter("dni_pos", dni_pos) :
                new ObjectParameter("dni_pos", typeof(string));
    
            var fecnac_posParameter = fecnac_pos.HasValue ?
                new ObjectParameter("fecnac_pos", fecnac_pos) :
                new ObjectParameter("fecnac_pos", typeof(System.DateTime));
    
            var sexo_posParameter = sexo_pos != null ?
                new ObjectParameter("sexo_pos", sexo_pos) :
                new ObjectParameter("sexo_pos", typeof(string));
    
            var telefono_posParameter = telefono_pos != null ?
                new ObjectParameter("telefono_pos", telefono_pos) :
                new ObjectParameter("telefono_pos", typeof(string));
    
            var email_posParameter = email_pos != null ?
                new ObjectParameter("email_pos", email_pos) :
                new ObjectParameter("email_pos", typeof(string));
    
            var direccion_posParameter = direccion_pos != null ?
                new ObjectParameter("direccion_pos", direccion_pos) :
                new ObjectParameter("direccion_pos", typeof(string));
    
            var usureg_posParameter = usureg_pos != null ?
                new ObjectParameter("usureg_pos", usureg_pos) :
                new ObjectParameter("usureg_pos", typeof(string));
    
            var codcargo_posParameter = codcargo_pos.HasValue ?
                new ObjectParameter("codcargo_pos", codcargo_pos) :
                new ObjectParameter("codcargo_pos", typeof(int));
    
            var coddis_posParameter = coddis_pos.HasValue ?
                new ObjectParameter("coddis_pos", coddis_pos) :
                new ObjectParameter("coddis_pos", typeof(int));
    
            var codpre_posParameter = codpre_pos.HasValue ?
                new ObjectParameter("codpre_pos", codpre_pos) :
                new ObjectParameter("codpre_pos", typeof(int));
    
            var coddoc_posParameter = coddoc_pos.HasValue ?
                new ObjectParameter("coddoc_pos", coddoc_pos) :
                new ObjectParameter("coddoc_pos", typeof(int));
    
            var codmaster_posParameter = codmaster_pos.HasValue ?
                new ObjectParameter("codmaster_pos", codmaster_pos) :
                new ObjectParameter("codmaster_pos", typeof(int));
    
            var codcen_posParameter = codcen_pos.HasValue ?
                new ObjectParameter("codcen_pos", codcen_pos) :
                new ObjectParameter("codcen_pos", typeof(int));
    
            var estado_posParameter = estado_pos.HasValue ?
                new ObjectParameter("estado_pos", estado_pos) :
                new ObjectParameter("estado_pos", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarPostulante", nom_posParameter, apell_posParameter, dni_posParameter, fecnac_posParameter, sexo_posParameter, telefono_posParameter, email_posParameter, direccion_posParameter, usureg_posParameter, codcargo_posParameter, coddis_posParameter, codpre_posParameter, coddoc_posParameter, codmaster_posParameter, codcen_posParameter, estado_posParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_Servicio_Procesos_Result> sp_Servicio_Procesos(Nullable<System.DateTime> fecini, Nullable<System.DateTime> fecfin)
        {
            var feciniParameter = fecini.HasValue ?
                new ObjectParameter("fecini", fecini) :
                new ObjectParameter("fecini", typeof(System.DateTime));
    
            var fecfinParameter = fecfin.HasValue ?
                new ObjectParameter("fecfin", fecfin) :
                new ObjectParameter("fecfin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Servicio_Procesos_Result>("sp_Servicio_Procesos", feciniParameter, fecfinParameter);
        }
    
        public virtual ObjectResult<sp_Servicio_Seleccion_Result> sp_Servicio_Seleccion(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Servicio_Seleccion_Result>("sp_Servicio_Seleccion", codeParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
