//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Recruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PROCESOS
    {
        public int codProceso { get; set; }
        public int codPostulante { get; set; }
        public bool Resultado_Proceso { get; set; }
    }
}
