//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Recruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERIENCIA
    {
        public int codExperiencia { get; set; }
        public System.DateTime Fec_ini { get; set; }
        public System.DateTime Fec_Ter { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> codGiro { get; set; }
        public Nullable<int> codCargo { get; set; }
        public Nullable<int> codPostulante { get; set; }
    }
}
