//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Recruiter
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string Login_Usuario { get; set; }
        public string Pass_Usuario { get; set; }
        public Nullable<bool> Nivel { get; set; }
        public Nullable<bool> Estado { get; set; }
        public System.DateTime Fec_Reg { get; set; }
        public string Usu_Reg { get; set; }
    }
}
